sonar.projectKey=MGTheTrain_multimedia-management-components
sonar.organization=mgtt
sonar.host.url=https://sonarcloud.io
sonar.projectName=multimedia-management-components
sonar.projectVersion=0.1.0
sonar.sources=crates
sonar.exclusions=**/target/**,**/generated/**
sonar.cpd.exclusions=**/tests/**
sonar.coverage.exclusions=**/tests/**
sonar.rust.lcov.reportPaths=coverage/domain/lcov.info,coverage/parsers/lcov.info,coverage/application/lcov.info,coverage/blob-storage-connector/lcov.info,coverage/persistence/lcov.info
